### PR TITLE
Add width/height getters

### LINKED ISSUE #38: Add programmatic width,height,pixelRatio getters
```
ctx.gl.drawingBufferWidth -> ctx.width
```

### PR DESCRIPTION
**Pull request by dmnsgn**
Fix #38

### CODE REVIEW

**Comment by dmnsgn** [comment]
Do you prefer getters or function return?

**Comment by vorg** [comment]
Getters for constituency with eg tex.width

**Comment by vorg** [comment]
This PR should include docs

**Comment by dmnsgn** [comment]
@vorg  Updated the PR

**Pull request closed without merging**
